name: CI

on:
    push:
        paths-ignore: ['**/*.md', '^\.*', 'LICENSE']
    pull_request:
        paths-ignore: ['**/*.md', '^\.*', 'LICENSE']

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout V (vlang/v) into subfolder
        uses: actions/checkout@v4
        with:
          repository: vlang/v
          path: v

      - name: Build V compiler
        run: |
          cd v
          make
          sudo cp v /usr/local/bin/v
          sudo chmod +x /usr/local/bin/v
          echo "VLIB_PATH=$(pwd)/vlib" >> $GITHUB_ENV
        shell: bash
      - name: Build vscript
        run: |
          # compile the main file into ./vscript
          v -o ./vscript src/main.v
        shell: bash

      - name: Make vscript executable
        run: chmod +x ./vscript
        shell: bash

      - name: Run basic functionality tests
        run: |
          ./vscript tests/test_simple.vs
          ./vscript tests/check_net.vs
          ./vscript tests/test_bind.vs
        shell: bash

      - name: Test transpilation to JavaScript
        run: |
          ./vscript --js tests/test_simple.vs > test_simple.js
          node --check test_simple.js
          ./vscript --js tests/test_bind.vs > test_bind.js
          node --check test_bind.js
        shell: bash
